# Generated by Django 6.1.1 on 2026-09-30 07:46

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='ชื่อหมวดหมู่')),
                ('description', models.TextField(blank=True, null=True, verbose_name='รายละเอียดหมวดหมู่')),
            ],
            options={
                'verbose_name': 'หมวดหมู่สินค้า',
                'verbose_name_plural': 'หมวดหมู่สินค้า',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='ชื่อจุดจำหน่าย')),
                ('building', models.CharField(max_length=100, verbose_name='อาคาร/ชื่ออาคาร')),
                ('floor', models.CharField(max_length=30, verbose_name='ชั้น')),
                ('room', models.CharField(max_length=100, verbose_name='ห้องหรือบริเวณ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='รายละเอียดสถานที่')),
            ],
            options={
                'verbose_name': 'สถานที่จำหน่าย',
                'verbose_name_plural': 'สถานที่จำหน่าย',
                'db_table': 'locations',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('Admin', 'Admin (ผู้ดูแลระบบ)'), ('Staff', 'Staff (พนักงานประจำสถานที่)')], default='Staff', max_length=30, verbose_name='สิทธิ์ผู้ใช้งาน')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้างบัญชี')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='shop_api.location', verbose_name='สถานที่รับผิดชอบ ( null = Admin )')),
            ],
            options={
                'verbose_name': 'ผู้ใช้งาน',
                'verbose_name_plural': 'ผู้ใช้งาน',
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='ชื่อสินค้า')),
                ('description', models.TextField(blank=True, null=True, verbose_name='รายละเอียดสินค้า')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ราคาสินค้า')),
                ('image_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='URL รูปภาพสินค้า')),
                ('reservable', models.BooleanField(default=True, verbose_name='รองรับการจองหรือไม่ (1=ได้, 0=ไม่ได้)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่เพิ่มสินค้า')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop_api.category', verbose_name='หมวดหมู่')),
            ],
            options={
                'verbose_name': 'สินค้า',
                'verbose_name_plural': 'สินค้า',
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_code', models.CharField(max_length=30, unique=True, verbose_name='รหัสการจอง')),
                ('student_id', models.CharField(max_length=20, verbose_name='รหัสนักศึกษา/บุคลากร')),
                ('quantity', models.IntegerField(default=1, verbose_name='จำนวนที่จอง')),
                ('status', models.CharField(choices=[('reserved', 'จองแล้ว (Reserved)'), ('picked_up', 'รับสินค้าแล้ว (Picked Up)'), ('expired', 'หมดอายุ (Expired)'), ('cancelled', 'ยกเลิก (Cancelled)')], default='reserved', max_length=30, verbose_name='สถานะการจอง')),
                ('reserved_at', models.DateTimeField(auto_now_add=True, verbose_name='เวลาที่จอง')),
                ('expires_at', models.DateTimeField(verbose_name='เวลาหมดอายุ (4 ชม.)')),
                ('picked_up_at', models.DateTimeField(blank=True, null=True, verbose_name='เวลารับสินค้า')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='shop_api.location')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='shop_api.product')),
            ],
            options={
                'verbose_name': 'รายการจองสินค้า',
                'verbose_name_plural': 'รายการจองสินค้า',
                'db_table': 'reservations',
            },
        ),
        migrations.CreateModel(
            name='ProductLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField(default=0, verbose_name='จำนวนสินค้าคงเหลือ')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_locations', to='shop_api.location')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_locations', to='shop_api.product')),
            ],
            options={
                'verbose_name': 'Stock สินค้าตามจุดจำหน่าย',
                'verbose_name_plural': 'Stock สินค้าตามจุดจำหน่าย',
                'db_table': 'product_locations',
                'unique_together': {('product', 'location')},
            },
        ),
    ]
